### ISSUE TITLE
works without having to rebuild the project?

### ISSUE THREAD

**Issue by davidliegar** [nuxt-community/dynamic-i18n#1]
I'm trying to make it work in my application.
Its work fine expect I always have to restart the server and make a new nuxt build in order to get the new JSON files.  Can I have dynamic translations without having to do that?

there is an example of use?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/dynamic-i18n/issues/c1">#c1</a>)</em></sub></div>

**Comment by gaetansenn** [comment]
Hello @davidliegar,

We are currently working on this issue and will keep you in touch ASAP.

Thank you for your feedback.

Regards,

**Comment by davidliegar** [comment]
thanks for the quick reply.   I'll be waiting :)

**Comment by gaetansenn** [comment]
Hello @davidliegar a new version of dynamic-i18n has been published with the fix.

https://github.com/nuxt-community/dynamic-i18n/tree/v1.0.1

The version is also available on npm.

PS: A new star on the repo is always welcome :slightly_smiling_face: 

Regards,
